# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-26 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20170613_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='followee',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='follower',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
