# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-26 20:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20170926_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='attachments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todolist.Media'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
